### PR TITLE
Add GitHub webhook endpoint to send events to Discord

### PR DESCRIPTION
**Pull request by teeberg**
image
## Setup
- Create a discord app: https://discordapp.com/developers/applications/me/create
- Define its bot token as `DISCORD_TOKEN` in `LSP_SECRETS`
- Set the discord channel to send events to by defining a `DISCORD_CHANNEL` in `LSP_SECRETS` and setting it to that channel's ID. You can get the channel ID from the URL when looking at a channel:
  image
- Give it access to the LMMS discord server by going to `https://discordapp.com/oauth2/authorize?client_id=<client_id>&scope=bot`
- Add GitHub Webhooks pointing to https://lmms.io/hooks/github/ to e.g. the LMMS and lmms.io repositories. Use a hard-to-guess secret and define it as `GITHUB_HOOK_SECRET` in `LSP_SECRETS`

### CODE REVIEW

**Comment by tresf** [comment]
1. What is the context of this PR (Who said they wanted this?  why the dev channel? Can we please vote against robot spam? Are 100s of emails not enough that we also need to track this on our dev channel?)
2. I assume this design was chosen because GitHub couldn't just [hook directly into](https://cloud.githubusercontent.com/assets/6345473/19062378/9f4c2740-89c7-11e6-888c-198a57efe95b.png) discord?

**Comment by teeberg** [comment]
1. We talked about this last week or so in discord. I thought people wanted it! If not, please close.
2. Not that I know of

**Comment by tresf** [comment]
> We talked about this last week or so in discord. I thought people wanted it! If not, please close.

I find "we discussed this elsewhere" STILL insufficient context.  Can you please shed light on this subject without the need for the web developers to attempt to locate such discussion?

**Comment by teeberg** [comment]
I don't actually know how to link to a message in discord. It was on September 25 at 9:23 am:
image

**Comment by tresf** [comment]
> @grejppi said:
> "I don't know if it's needed though

@grejppi, can you chime in here?  You and @Umcaruje spend a considerable amount of time on discord.  I assume there's a reasoning behind this, is it to avoid using email notifications for you personally, or is it to help live-stream changes and requests?  I feel this may turn a bit into an ["interrupting cow"](http://uncyclopedia.wikia.com/wiki/Interrupting_cow).

**Comment by grejppi** [comment]
Yeah, personally I don't feel a strong need for this. Why I brought it up back then was mostly because strong GitHub integration was lost in the move from Gitter to Discord.

**Comment by Umcaruje** [comment]
Now that discord supports webhooks, is there a need for this?
 https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks

**Comment by tresf** [comment]
> Now that discord supports webhooks, is there a need for this?


Agreed.  Closing this PR due to obsolescence.

Here's a tutorial to use that which is now built-in:

https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22

**Pull request closed without merging**
