### PR TITLE
Changed documentation to redirect to GitBook

### PR DESCRIPTION
**Pull request by quaeched**

### CODE REVIEW

**Comment by tresf** [comment]
Screenshot for reference: 
Screen Shot 2019-12-01 at 1 18 24 PM

**Comment by tresf** [comment]
@lukas-w this turns off the documentation embedding, but I think it's a good trade-off as it makes  wiki contributions easier.  Thoughts?

@iansannar you're our YouTube guy, any comments or suggestions?

**Comment by tresf** [comment]
Quoting @iansannar from Discord:

> I have been periodically looking through it as he adds stuff. Content is excellent. Tone and structure consistency needs some work, but that's a minor nitpick. I can do a thorough review sometime this week.
Sorry I haven't been hardly active lately. Been figuring some health issues out. Hopefully I'll be able to get back into supporting this community soon

**Comment by Umcaruje** [comment]
First of all @quaeched, great work! Glad the documentation is getting the long-awaited refresh. Talked a bit about this PR with @tresf on discord. Here's the gist:

1. It would be nice that the documentation resides on a subdomain like `docs.lmms.io` @tresf has contacted our hosting operator about adding a DNS mapping. Gitbook supports Let's encrypt so we should be able to set this up pretty easily. 

1. We need to set up redirects for the current most visited pages of our documentation. I don't think there's a way to do this automatically because the URLs are quite different, but this would be a list of redirects using silex e.g. `lmms.io/documentation/Getting_Started --> docs.lmms.io/2-getting-started`. Research should be done to see what pages are the most visited and how extensive this list should be. 

1. Also, I would change the navbar to directly link to the new subdomain, and not to `lmms.io/documentation` which would then redirect.

**Comment by quaeched** [comment]
@Umcaruje Thank You for the feedback! 

1. I agree.
2. If we remove numbering from the slugs, which we can easily do inside GitBook, I believe the process of redirection could be automated.
3. In 49ed698 I changed the redirection to a direct link.

**Comment by tresf** [comment]
NetworkRedux got back to us with directions for configuring DNS.

https://docs.gitbook.com/hosting/custom-domains

I've added a `CNAME` record for `docs` which points to `hosting.gitbook.com.`.  It can take up to a day to propagate.  Once it's done, GitBook appears to automatically configure the HTTPS cert for us (using LetsEncrypt).  I'll let you know once the new URL is working.

**Comment by tresf** [comment]
https://docs.lmms.io/ is now live.

**Comment by tresf** [comment]
Why was this closed?

**Comment by tresf** [comment]
I found the reason on Discord:

> I'm gonna close my PR now that the port is coming, okay?

Next time, please offer a description for closing.

**Comment by quaeched** [comment]
Oh, sorry. I'll remember ;)

**Comment by lukas-w** [comment]
@tresf 
> this turns off the documentation embedding, but I think it's a good trade-off as it makes wiki contributions easier. Thoughts?

I'd be happy to take a look at writing a GitBook embedding if it's desired. Even though GitBook claims on their homepage that they provide "Powerful APIs", I can't find any way to access the GitBook's data programmatically. Maybe the only way is to enable GitHub syncing and base the embedding on the synced git repo. 

image

**Comment by tresf** [comment]
> I'd be happy to take a look at writing a GitBook embedding if it's desired. Even though GitBook claims on their homepage that they provide "Powerful APIs", I can't find any way to access the GitBook's data programmatically. Maybe the only way is to enable GitHub syncing and base the embedding on the synced git repo.

I've reached out to support to see if there's something we're missing.  In the meantime, I vote that we temporarily disabling embedding while this gets worked out.  I'm also not opposed to scrapping the idea of embedding period as it inevitably introduced more code to maintain moving forward.

> I'm gonna close my PR now that the port is coming, okay?

I assume you mean this port? https://github.com/LMMS/lmms.io/pull/285/files

@quaeched @liushuyu can you explain what about this PR supersedes this PR?  Since we've closed this PR, it's unobvious where GitBook conversation should occur, I see no mention of it in #285.

**Comment by tresf** [comment]
@lukas-w GitBook replied with the following:

> We actually don't have an API for now  it is indeed only possible via GitBook at the moment but are gathering information based on user feedback to see what we should be working on exactly.
>
> Could you please let me know how you'd like to interact with our services via an API?
What are you expecting exactly?

I answered with the general description of what we'd be interested in (non-technical).  If you'd like to add to this conversation, let me know.

**Comment by liushuyu** [comment]
>@quaeched @liushuyu can you explain what about this port supersedes this PR? Since we've closed this PR, it's unobvious where GitBook conversation should occur, I see no mention of it in #285.

There it is: https://github.com/LMMS/lmms.io/pull/285/files#diff-fb9d9a99e07358693beb67949d467045R12

**Comment by tresf** [comment]
> > I'd be happy to take a look at writing a GitBook embedding if it's desired. Even though GitBook claims on their homepage that they provide "Powerful APIs", I can't find any way to access the GitBook's data programmatically. Maybe the only way is to enable GitHub syncing and base the embedding on the synced git repo.

@lukas-w GitBook replied with the following:

> A feature request for an API has been opened on Canny (our roadmap tool), I recommend you to follow this request in order to be updated if we have any news on this topic.
> https://gitbook.canny.io/feature-requests/p/http-api-to-access-and-update-content

**Pull request closed without merging**
