### PR TITLE
Add email address on competitions page

### PR DESCRIPTION
**Pull request by Spekular**
I've ended up doing most of the communication with submitters when there are problems (broken links, invalid entries, etc.). Right now I'm asking for project files from some artists to confirm that their submissions are made with LMMS. Listing my email on the competitions page should lend me some credibility so submitters don't think I'm trying to steal their project files.

### CODE REVIEW

**Comment by tresf** [comment]
@Spekular why not just give yourself an `lmms.io` address?

**Comment by Spekular** [comment]
Not a clue how to do that, and I think umcaruje said we don't have any.

**Comment by Umcaruje** [comment]
I have no idea if we can send emails from lmms.io

**Comment by tresf** [comment]
> I have no idea if we can send emails from lmms.io

Gmail removed the option to do this a few years ago so no, it won't work without setting up email forwarding through NetworkRedux.

I'll merge this for now, but we should work with NetworkRedux to set up `competitions@lmms.io` as a valid address for next year.

**Comment by tresf** [comment]
@Spekular opened new issue here https://github.com/LMMS/lmms.io/issues/226 to track how we can tackle this in the future.

**Comment by Spekular** [comment]
@tresf :+1: soubds good to me

**Pull request merged**
