### PR TITLE
Add a Competitions page

### LINKED ISSUE #151: Best Of LMMS Vol 2
1. We should probably put the official rules on our home page.
 1. ~~Last years competition should have a link to the new one somewhere in the description.~~(Edit: fixed by Uroš)
 1. We should make the SC URLs similar so people can expect to be able to change the URL to v1, v2, v3 etc. `lmms-top-songs-compilation` is quite different from `the-best-of-lmms-competition-v2`

https://soundcloud.com/groups/lmms-top-songs-compilation

https://soundcloud.com/groups/the-best-of-lmms-competition-v2

@Umcaruje  @sti2nd

### PR DESCRIPTION
**Pull request by Umcaruje**
Fixes #151 

@sti2nd @tresf  any thoughts before I merge this?

Screenshots: 

Collapsed 
collapsed

Expanded
expanded

### CODE REVIEW

**Comment by tresf** [comment]
Nice work @Umcaruje.

I still think the style of this should more closely reflect our "Get Involved" page (mockup below).

I also think the headers being full size images are a bad idea and the idea of collapsing them has no visual indicator as to how or why, which I think could be improved.

But something is better than nothing... we can always improve it later I suppose. :)

image

**Comment by Sti2nd** [comment]
I like it really much! Love the images :)

**Comment by Umcaruje** [comment]
Added a dropdown indicator. See it in action:

http://youtu.be/JWFRCYVr9aw

Any other thoughs or I should merge this?

**Comment by tresf** [comment]
Thanks for the screencast.  I still strongly believe this page has continuity problems with the rest of our site layout, site navigation as well as sight design.  I think the rules should be static on the page and the competitions should be links.  I don't feel the tracks belong there either when we can just link to the results.

**Comment by tresf** [comment]
That said, I'm sure you want to get this out there, so do as you wish. :+1:

**Comment by Sti2nd** [comment]
> I don't feel the tracks belong there either when we can just link to the results.

Yeah, I too was thinking this is great, we could actually replace the showcase section with the competition page, but then we would have no showcase tab, and being a showcase tab with music was perhaps not the intention of the new competition tab..? So maybe the look/page you made, Uros, could be the new showcase page, and the look Tres is suggesting is better suited for the competition tab?

Tres knows more about keeping sites tidy, but I love that we make use of the album art as headers! Personally I am not sure "get involved" and "competitions" have so much in common it is important for them to look the same :)

**Comment by Umcaruje** [comment]
Ok so, since the deadline is closing in for BoLv2, I will merge this now. 

As for the inconsistency with the showcase and get involved pages, we can work something out later, when the compo is over :)

**Comment by tresf** [comment]
:)

**Pull request merged**
