### PR TITLE
Update favicon

### PR DESCRIPTION
**Pull request by iansannar**

### CODE REVIEW

**Comment by tresf** [comment]
The favicon format is one of the worst documented and changes year after year.  I'm merging this (sorry @iansannar it should have been merged sooner).  If it breaks something, I assume you'll be the one fixing it.

**Comment by DomClark** [comment]
This doesn't seem to have any effect as the actual favicon is specified to be [public/img/logo_sm.png](https://github.com/LMMS/lmms.io/blob/83bdd4370b8df3532b86d636c3c8b077f95c835a/public/img/logo_sm.png):
https://github.com/LMMS/lmms.io/blob/2ad936c5c9b32f46d9c0adea3c9027a150de5abb/templates/head.twig#L10

Also, the favicon has changed from a 1.12KB file containing only a 16x16 image, to a 401KB file containing 16x16, 24x24, 32x32, 48x48, 64x64, 96x96, 128x128 and 256x256 images. Is this desirable?

(Sorry I didn't see this before it was merged, I don't usually pay attention to this repo.)

**Comment by iansannar** [comment]
> the actual favicon is specified to be [public/img/logo_sm.png](https://github.com/LMMS/lmms.io/blob/83bdd4370b8df3532b86d636c3c8b077f95c835a/public/img/logo_sm.png):
Whoops. I should have checked. I'll have to redo this then. Is favicon.ico used at all? Is it beneficial to keep it around if it isn't?

**Comment by tresf** [comment]
> the favicon has changed from a 1.12KB file containing only a 16x16 image, to a 401KB file containing 16x16, 24x24, 32x32, 48x48, 64x64, 96x96, 128x128 and 256x256 images. Is this desirable?

Probably.  Depends on your opinion. Like I said, it's poorly documented and constantly changing.  The 16x16 icons will look like trash if used for anything except a standard DPI tab icon.  Once they're added as app launchers, dragged as desktop icons, etc, they start to look like crap.

> Also, the favicon has changed from a 1.12KB file containing only a 16x16 image,

Well, it's actually a 24x24 icon in twig, 16x16 in the fallback location.

> This doesn't seem to have any effect as the actual favicon is specified to be public/img/logo_sm.png:

Good catch, but then we should just change the template.  If someone has a problem with the file size, we can ask @iansannar to shrink it.  Last I remember, the favicon is fetched asynchronously so it shouldn't slow page loads.

```diff
- <link rel="icon" type="image/png" href="/img/logo_sm.png"> 
+ <link rel="icon" type="image/x-icon" href="/favicon.ico" />
```

**Pull request merged**
