### PR TITLE
Updated LSP login sidebar (CSS layout)

### PR DESCRIPTION
**Pull request by QrchackOfficial**
Centered login button and register link, improved spacing

Before:
2016-12-17 22_20_07-lmms share

After:
2016-12-17 22_20_00-lmms share

### CODE REVIEW

**Comment by tresf** [comment]
The spacing is a nice addition, but the rest is inconsistent with the rest of the site.  Please advise.

screen shot 2016-12-17 at 5 33 29 pm

**Comment by QrchackOfficial** [comment]
Reverted `text-center` for now

**Comment by tresf** [comment]
If you remove the unnecessary code, this can be merged.  Otherwise let us know if you're still working at it.

**Comment by QrchackOfficial** [comment]
That'd be it for now, can probably check back in later on if time allows.

**Pull request merged**
