### PR TITLE
Groups no longer exist on SoundCloud

### PR DESCRIPTION
**Pull request by Bobhostern**
Since groups don't actually seem to exist on SoundCloud, I simply found the link for the SoundCloud "lmmsio" account, and replaced the URL there. This was a really quick and easy edit hopefully.

### CODE REVIEW

**Comment by tresf** [comment]
@Bobhostern perhaps something like searching `#lmms` tags instead?  Our soundcloud page is rather dry.  Example: https://soundcloud.com/search/sounds?q=%23lmms

**Comment by Bobhostern** [comment]
https://soundcloud.com/search/sounds?q=lmms maybe?

**Comment by tresf** [comment]
Sure

**Comment by Bobhostern** [comment]
I've now changed it. Is it better?

**Pull request merged**
