### PR TITLE
Revised few translations

### PR DESCRIPTION
**Pull request by LeSeulArtichaut**

### CODE REVIEW

**Comment by Spekular** [comment]
Thanks for the contributions! We usually do translations via [Transifex](https://www.transifex.com/lmms/lmms/) though, so I think you should submit them there.

**Comment by LeSeulArtichaut** [comment]
> We usually do translations via [Transifex](https://www.transifex.com/lmms/lmms/) though

Oh, you're right. Sorry, I didn't even notice. I've opened a request for joining the Tx team.

**Comment by Spekular** [comment]
You may as well, probably. Maybe you could leave it open until your request is accepted though?

**Comment by liushuyu** [comment]
Sorry for the late response, https://www.transifex.com/user/profile/LeSeulArtichaut/ joined the Transifex team.

PR closed.

**Pull request closed without merging**
