### PR TITLE
Edited the get involved text to make it flow better

### PR DESCRIPTION
**Pull request by SecondFlight**

### CODE REVIEW

**Comment by tresf** [comment]
Hmm... I'll let @Lukas-W approve these as he originally wrote them.  His sentences are grammatically correct, so it is really a matter of preference, one that I'll let him decide.

I don't particularly like the extra commas in the first sentence, personally.  The rest seems to me to be fine though.

-Tres

**Comment by SecondFlight** [comment]
You can remove those commas if you want.

**Comment by tresf** [comment]
> You can remove those commas if you want.

Sure, but that tends to defeat the purpose of a pull request, no? :)

**Comment by SecondFlight** [comment]
Okay :3

**Comment by tresf** [comment]
> How's this? 

:+1:  :)

I'll still leave the rest for Lukas though, since he authored it. :)

**Comment by Spekular** [comment]
If it counts, I like these changes. "...and help making LMMS better"
especially sounds awkward to me. I'm still not sure about "We are in
desperate need of new developers to join our team". It sounds desperate (
duh ;p ), which makes it sound less professional. Also, just for
consideration, what do you think of "the team" rather than "our team"
(connotation/impression wise, both are obviously correct).

**Comment by Sti2nd** [comment]
> which makes it sound less professional.

That is what we want! People demand too much without involving, much thanks to me for being too professional on LMMS FB. I would never got involved in a project which seemed to have a lot of clever people and above my level.

**Comment by Spekular** [comment]
@sti2nd I was thinking about that too but it still feels odd to call LMMS
"desperate". Its great for conveying that we really need contributors
though, which we do, so I guess you're right.

**Comment by Lukas-W** [comment]
"Desperate" may sound desperate, but I think it's accurate.

**Comment by Lukas-W** [comment]
Oh and I'm fine with the changes proposed here, as long as a native English speaker (Tres) nods it through. ;)

**Comment by SecondFlight** [comment]
Well, as a native speaker, I can confirm that they work. Also this:

>I don't particularly like the extra commas in the first sentence, personally. The rest seems to me to be fine though.

And after I fixed the commas:

>:+1: :)

**Comment by SecondFlight** [comment]
Ah, there we go. :)

**Comment by tresf** [comment]
... And yes, we are desperate.  A little less now with the addition of a few new developers but if our open/close ratio for bugs on the LMMS repo is a sign, we need help and we do need it desperately.

... most of our developers first start as users, so this message is just as relevant to the existing community as it is to the new community members. :heart:

**Pull request merged**
