### PR TITLE
Jumbo headers everywhere

### PR DESCRIPTION
**Pull request by Lukas-W**
How about having this sexy jumbo header not only on the main page, but serving as a container for every page's title?

I think it looks good, but I'm not that sure of it myself, so please share your opinions :)

screen shot 2014-11-07 at 23 45 01
screen shot 2014-11-07 at 23 44 43
screen shot 2014-11-01 at 23 47 26
screen shot 2014-11-01 at 23 47 30

Please excuse the screenshot spam.

### CODE REVIEW

**Comment by Umcaruje** [comment]
Is there any progress on this?

**Comment by Lukas-W** [comment]
Nope… I only got screen shots lying around of one of the headers I suggested above, but a little bit smaller.

screen shot 2015-02-08 at 22 04 29
screen shot 2015-02-08 at 22 04 41

**Comment by tresf** [comment]
Is this still desired?  Shall we close and reopen at a later time? :+1: / :-1:  ?

**Comment by Umcaruje** [comment]
I say I really like this, and it looks really neat to me. I'd rather use the lovely hexagon pattern than the floral one for the smaller jumbos. I would love to see this rebased and merged.

**Comment by tresf** [comment]
>  I'd rather use the lovely hexagon pattern than the floral one for the smaller jumbos. I would love to see this rebased and merged.

I tried a mockup of a hexagon one.. never got it to look right.  :sob:

**Comment by Umcaruje** [comment]
>I tried a mockup of a hexagon one.. never got it to look right. 

Well there should just be a simple hexagon tile, and a CSS gradient over it. That's my idea.
I can fiddle with it if you want to.  :) I just need the tile.

**Comment by tresf** [comment]
> I just need the tile.

Ok... I'm confused by this line... do you need something from me?

**Comment by Umcaruje** [comment]
Well, I need it from Lukas. Unless its already on the branch, I haven't checked.

**Comment by tresf** [comment]
I'm still confused... Our existing jumbotron is already tiled.... Is that what you are referring to?

**Comment by Umcaruje** [comment]
I'm referring to the Hexagon pattern that Lukas used in his mockups.

**Comment by Lukas-W** [comment]
PNG (a bit dark): pattern
SVG: https://gist.github.com/Lukas-W/c65a8ca8c9135277d7a6

**Comment by Umcaruje** [comment]
Thanks, I'll do some mockups tommorow, when I have the time. If you don't beat me to it :)

**Comment by tresf** [comment]
> I'm referring to the Hexagon pattern that Lukas used in his mockups.

Oh yes from the first post (I thought I looked there, sorry).

I still don't care for that tile much by itself personally (for what it's worth).

**Comment by tresf** [comment]
I'm closing this PR out as it offers very little staying open currently (stale for over a year)... we can always reopen it at a later time if needed.

**Pull request closed without merging**
